# Configuration for the 'builder' tool
#

MODULE = liblog
TARGET = liblog.so liblog.a

H_INSTALL_FILES = log.h

liblog_dep = log.o

TESTS = test_log
test_log_dep = test_log.o log

CPPFLAGS := $(CPPFLAGS) -fPIC
